version: '3.8'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.dev
  #   container_name: nest-api
  #   environment:
  #     - PORT=3000
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/api/src
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    container_name: postgres-db
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db  

      
